# Generated by Django 4.2.7 on 2025-11-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_disable',
            field=models.BooleanField(default=False, help_text='Automatically disable tenant on expiration date'),
        ),
        migrations.AddField(
            model_name='client',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Optional expiration date for tenant access', null=True),
        ),
    ]
